import mods.tcomplement.Blacklist;
import mods.tcomplement.Overrides;
import mods.tconstruct.Melting;

//Add smeltery recipes

//Geolosys
Melting.addRecipe(<liquid:iron> * 144, <geolosys:cluster>);
Melting.addRecipe(<liquid:gold> * 144, <geolosys:cluster:1>);
Melting.addRecipe(<liquid:copper> * 144, <geolosys:cluster:2>);
Melting.addRecipe(<liquid:tin> * 144, <geolosys:cluster:3>);
Melting.addRecipe(<liquid:silver> * 144, <geolosys:cluster:4>);
Melting.addRecipe(<liquid:lead> * 144, <geolosys:cluster:5>);
Melting.addRecipe(<liquid:nickel> * 144, <geolosys:cluster:7>);
Melting.addRecipe(<liquid:platinum> * 144, <geolosys:cluster:8>);
Melting.addRecipe(<liquid:uranium> * 144, <geolosys:cluster:9>);
Melting.addRecipe(<liquid:zinc> * 144, <geolosys:cluster:10>);
Melting.addRecipe(<liquid:osmium> * 144, <geolosys:cluster:12>);

//Melter Recipe removal
Overrides.removeRecipe(<liquid:iron>);
Overrides.removeRecipe(<liquid:gold>);
Overrides.removeRecipe(<liquid:platinum>);
Overrides.removeRecipe(<liquid:silver>);
Overrides.removeRecipe(<liquid:lead>);
Overrides.removeRecipe(<liquid:obsidian>);
Overrides.removeRecipe(<liquid:iridium>);
Overrides.removeRecipe(<liquid:pigiron>);
Overrides.removeRecipe(<liquid:cobalt>);
Overrides.removeRecipe(<liquid:steel>);
Overrides.removeRecipe(<liquid:ardite>);
Overrides.removeRecipe(<liquid:manyullyn>);
Overrides.removeRecipe(<liquid:emerald>);
Overrides.removeRecipe(<liquid:nickel>);
Overrides.removeRecipe(<liquid:electrum>);
Overrides.removeRecipe(<liquid:invar>);
Overrides.removeRecipe(<liquid:constantan>);
Overrides.removeRecipe(<liquid:knightslime>);
Overrides.removeRecipe(<liquid:alubrass>);
Overrides.removeRecipe(<liquid:aluminum>);
Overrides.removeRecipe(<liquid:dragonsteel_fire>);
Overrides.removeRecipe(<liquid:dragonsteel_ice>);
Overrides.removeRecipe(<liquid:signalum>);
Overrides.removeRecipe(<liquid:lumium>);
Overrides.removeRecipe(<liquid:enderium>);
Overrides.removeRecipe(<liquid:uranium>);
Overrides.removeRecipe(<liquid:knightmetal>);

Blacklist.addRecipe(<liquid:terrasteel>, <botania:storage:1>);
Blacklist.addRecipe(<liquid:terrasteel>, <botania:manaresource:4>);
Blacklist.addRecipe(<liquid:terrasteel>, <botania:manaresource:18>);
Blacklist.addRecipe(<liquid:manasteel>, <botania:manaresource:17>);
Blacklist.addRecipe(<liquid:manasteel>, <botania:manaresource>);
Blacklist.addRecipe(<liquid:manasteel>, <botania:storage>);
Blacklist.addRecipe(<liquid:elementium>, <botania:storage:2>);
Blacklist.addRecipe(<liquid:elementium>, <botania:manaresource:7>);
Blacklist.addRecipe(<liquid:elementium>, <botania:manaresource:19>);
Blacklist.addRecipe(<liquid:starmetal>, <astralsorcery:blockcustomore:1>);
Blacklist.addRecipe(<liquid:starmetal>, <astralsorcery:itemcraftingcomponent:1>);
Blacklist.addRecipe(<liquid:starmetal>, <astralsorcery:itemcraftingcomponent:2>);
Blacklist.addRecipe(<liquid:thaumium>, <thaumcraft:metal_thaumium>);
Blacklist.addRecipe(<liquid:thaumium>, <thaumcraft:plate:2>);
Blacklist.addRecipe(<liquid:thaumium>, <thaumcraft:nugget:6>);
Blacklist.addRecipe(<liquid:thaumium>, <thaumcraft:ingot>);
Blacklist.addRecipe(<liquid:voidmetal>, <thaumcraft:nugget:7>);
Blacklist.addRecipe(<liquid:voidmetal>, <thaumcraft:ingot:1>);
Blacklist.addRecipe(<liquid:voidmetal>, <thaumcraft:metal_void>);
Blacklist.addRecipe(<liquid:signalum>, <thermalfoundation:storage_alloy:5>);
Blacklist.addRecipe(<liquid:signalum>, <thermalfoundation:material:101>);
Blacklist.addRecipe(<liquid:signalum>, <thermalfoundation:material:165>);
Blacklist.addRecipe(<liquid:signalum>, <thermalfoundation:material:229>);
Blacklist.addRecipe(<liquid:signalum>, <thermalfoundation:material:293>);
Blacklist.addRecipe(<liquid:signalum>, <thermalfoundation:material:357>);
Blacklist.addRecipe(<liquid:lumium>, <thermalfoundation:storage_alloy:6>);
Blacklist.addRecipe(<liquid:lumium>, <thermalfoundation:material:102>);
Blacklist.addRecipe(<liquid:lumium>, <thermalfoundation:material:166>);
Blacklist.addRecipe(<liquid:lumium>, <thermalfoundation:material:230>);
Blacklist.addRecipe(<liquid:lumium>, <thermalfoundation:material:294>);
Blacklist.addRecipe(<liquid:lumium>, <thermalfoundation:material:358>);
Blacklist.addRecipe(<liquid:enderium>, <thermalfoundation:storage_alloy:7>);
Blacklist.addRecipe(<liquid:enderium>, <thermalfoundation:material:103>);
Blacklist.addRecipe(<liquid:enderium>, <thermalfoundation:material:167>);
Blacklist.addRecipe(<liquid:enderium>, <thermalfoundation:material:231>);
Blacklist.addRecipe(<liquid:enderium>, <thermalfoundation:material:295>);
Blacklist.addRecipe(<liquid:enderium>, <thermalfoundation:material:359>);
Blacklist.addRecipe(<liquid:gold>, <thermalfoundation:tool.sickle_gold>);
Blacklist.addRecipe(<liquid:gold>, <minecraft:gold_ore>);
Blacklist.addRecipe(<liquid:gold>, <minecraft:golden_horse_armor>);
Blacklist.addRecipe(<liquid:gold>, <minecraft:golden_rail>);
Blacklist.addRecipe(<liquid:gold>, <exnihilocreatio:item_ore_gold:1>);
Blacklist.addRecipe(<liquid:gold>, <exnihilocreatio:item_ore_gold:2>);
Blacklist.addRecipe(<liquid:gold>, <adchimneys:gold_block>);
Blacklist.addRecipe(<liquid:gold>, <thermalfoundation:material:1>);
Blacklist.addRecipe(<liquid:gold>, <thermalfoundation:material:25>);
Blacklist.addRecipe(<liquid:gold>, <thermalfoundation:material:33>);
Blacklist.addRecipe(<liquid:gold>, <thermalfoundation:tool.bow_gold>);
Blacklist.addRecipe(<liquid:gold>, <thermalfoundation:tool.sickle_gold>);
Blacklist.addRecipe(<liquid:gold>, <geolosys:cluster:1>);
Blacklist.addRecipe(<liquid:gold>, <minecraft:gold_block>);
Blacklist.addRecipe(<liquid:gold>, <minecraft:gold_ingot>);
Blacklist.addRecipe(<liquid:gold>, <minecraft:golden_helmet>);
Blacklist.addRecipe(<liquid:gold>, <minecraft:golden_chestplate>);
Blacklist.addRecipe(<liquid:gold>, <minecraft:golden_leggings>);
Blacklist.addRecipe(<liquid:gold>, <minecraft:golden_boots>);
Blacklist.addRecipe(<liquid:gold>, <minecraft:gold_nugget>);
Blacklist.addRecipe(<liquid:gold>, <minecraft:light_weighted_pressure_plate>);
Blacklist.addRecipe(<liquid:gold>, <minecraft:clock>);
Blacklist.addRecipe(<liquid:gold>, <tconstruct:materials:15>);
Blacklist.addRecipe(<liquid:gold>, <exnihilocreatio:crook_gold>);
Blacklist.addRecipe(<liquid:gold>, <exnihilocreatio:hammer_gold>);
Blacklist.addRecipe(<liquid:gold>, <iceandfire:goldpile>);
Blacklist.addRecipe(<liquid:gold>, <iceandfire:dragonarmor_gold>);
Blacklist.addRecipe(<liquid:gold>, <iceandfire:dragonarmor_gold:1>);
Blacklist.addRecipe(<liquid:gold>, <iceandfire:dragonarmor_gold:2>);
Blacklist.addRecipe(<liquid:gold>, <iceandfire:dragonarmor_gold:3>);
Blacklist.addRecipe(<liquid:gold>, <thaumcraft:filter>);
Blacklist.addRecipe(<liquid:gold>, <thaumcraft:inlay>);
Blacklist.addRecipe(<liquid:gold>, <thermalfoundation:material:513>);
Blacklist.addRecipe(<liquid:iron>, <geolosys:cluster>);
Blacklist.addRecipe(<liquid:iron>, <adchimneys:iron_block>);
Blacklist.addRecipe(<liquid:iron>, <minecraft:chainmail_boots>);
Blacklist.addRecipe(<liquid:iron>, <minecraft:chainmail_helmet>);
Blacklist.addRecipe(<liquid:iron>, <minecraft:chainmail_chestplate>);
Blacklist.addRecipe(<liquid:iron>, <minecraft:chainmail_leggings>);
Blacklist.addRecipe(<liquid:iron>, <thermalfoundation:tool.sickle_iron>);
Blacklist.addRecipe(<liquid:iron>, <minecraft:iron_ore>);
Blacklist.addRecipe(<liquid:iron>, <minecraft:shears>);
Blacklist.addRecipe(<liquid:iron>, <minecraft:tripwire_hook>);
Blacklist.addRecipe(<liquid:iron>, <minecraft:shield>);
Blacklist.addRecipe(<liquid:iron>, <minecraft:minecart>);
Blacklist.addRecipe(<liquid:iron>, <minecraft:hopper>);
Blacklist.addRecipe(<liquid:iron>, <minecraft:heavy_weighted_pressure_plate>);
Blacklist.addRecipe(<liquid:iron>, <minecraft:compass>);
Blacklist.addRecipe(<liquid:iron>, <minecraft:cauldron>);
Blacklist.addRecipe(<liquid:iron>, <minecraft:bucket>);
Blacklist.addRecipe(<liquid:iron>, <minecraft:anvil>);
Blacklist.addRecipe(<liquid:iron>, <exnihilocreatio:crook_iron>);
Blacklist.addRecipe(<liquid:iron>, <iceandfire:dragonarmor_iron>);
Blacklist.addRecipe(<liquid:iron>, <iceandfire:dragonarmor_iron:1>);
Blacklist.addRecipe(<liquid:iron>, <iceandfire:dragonarmor_iron:2>);
Blacklist.addRecipe(<liquid:iron>, <iceandfire:dragonarmor_iron:3>);
Blacklist.addRecipe(<liquid:iron>, <iceandfire:chain_link>);
Blacklist.addRecipe(<liquid:iron>, <thermalfoundation:material:512>);
Blacklist.addRecipe(<liquid:iron>, <primal:slat_iron>);
Blacklist.addRecipe(<liquid:iron>, <minecraft:iron_horse_armor>);
Blacklist.addRecipe(<liquid:iron>, <minecraft:rail>);
Blacklist.addRecipe(<liquid:iron>, <minecraft:activator_rail>);
Blacklist.addRecipe(<liquid:iron>, <minecraft:detector_rail>);
Blacklist.addRecipe(<liquid:iron>, <tcomplement:sledge_head>.withTag({Material: "iron"}));
Blacklist.addRecipe(<liquid:iron>, <exnihilocreatio:item_ore_iron:1>);
Blacklist.addRecipe(<liquid:iron>, <exnihilocreatio:item_ore_iron:2>);
Blacklist.addRecipe(<liquid:iron>, <minecraft:iron_block>);
Blacklist.addRecipe(<liquid:iron>, <minecraft:iron_door>);
Blacklist.addRecipe(<liquid:iron>, <minecraft:iron_trapdoor>);
Blacklist.addRecipe(<liquid:iron>, <minecraft:iron_bars>);
Blacklist.addRecipe(<liquid:iron>, <structurize:sceptersteel>);
Blacklist.addRecipe(<liquid:iron>, <minecraft:iron_ingot>);
Blacklist.addRecipe(<liquid:iron>, <minecraft:iron_helmet>);
Blacklist.addRecipe(<liquid:iron>, <minecraft:iron_chestplate>);
Blacklist.addRecipe(<liquid:iron>, <minecraft:iron_leggings>);
Blacklist.addRecipe(<liquid:iron>, <minecraft:iron_boots>);
Blacklist.addRecipe(<liquid:iron>, <exnihilocreatio:hammer_iron>);
Blacklist.addRecipe(<liquid:iron>, <minecraft:iron_nugget>);
Blacklist.addRecipe(<liquid:iron>, <thermalfoundation:tool.sickle_iron>);
Blacklist.addRecipe(<liquid:iron>, <thermalfoundation:tool.bow_iron>);
Blacklist.addRecipe(<liquid:iron>, <thermalfoundation:material:32>);
Blacklist.addRecipe(<liquid:iron>, <thermalfoundation:material:24>);
Blacklist.addRecipe(<liquid:iron>, <thermalfoundation:material>);
Blacklist.addRecipe(<liquid:iron>, <tconstruct:sign_head>.withTag({Material: "iron"}));
Blacklist.addRecipe(<liquid:iron>, <tconstruct:pan_head>.withTag({Material: "iron"}));
Blacklist.addRecipe(<liquid:iron>, <tconstruct:scythe_head>.withTag({Material: "iron"}));
Blacklist.addRecipe(<liquid:iron>, <tconstruct:kama_head>.withTag({Material: "iron"}));
Blacklist.addRecipe(<liquid:iron>, <tconstruct:excavator_head>.withTag({Material: "iron"}));
Blacklist.addRecipe(<liquid:iron>, <tconstruct:hammer_head>.withTag({Material: "iron"}));
Blacklist.addRecipe(<liquid:iron>, <tconstruct:large_sword_blade>.withTag({Material: "iron"}));
Blacklist.addRecipe(<liquid:iron>, <tconstruct:sword_blade>.withTag({Material: "iron"}));
Blacklist.addRecipe(<liquid:iron>, <tconstruct:broad_axe_head>.withTag({Material: "iron"}));
Blacklist.addRecipe(<liquid:iron>, <tconstruct:binding>.withTag({Material: "iron"}));
Blacklist.addRecipe(<liquid:iron>, <tconstruct:tough_binding>.withTag({Material: "iron"}));
Blacklist.addRecipe(<liquid:iron>, <tconstruct:wide_guard>.withTag({Material: "iron"}));
Blacklist.addRecipe(<liquid:iron>, <tconstruct:hand_guard>.withTag({Material: "iron"}));
Blacklist.addRecipe(<liquid:iron>, <tconstruct:cross_guard>.withTag({Material: "iron"}));
Blacklist.addRecipe(<liquid:iron>, <tconstruct:large_plate>.withTag({Material: "iron"}));
Blacklist.addRecipe(<liquid:iron>, <tconstruct:knife_blade>.withTag({Material: "iron"}));
Blacklist.addRecipe(<liquid:iron>, <tconstruct:bow_limb>.withTag({Material: "iron"}));
Blacklist.addRecipe(<liquid:iron>, <tconstruct:arrow_head>.withTag({Material: "iron"}));
Blacklist.addRecipe(<liquid:iron>, <tconstruct:sharpening_kit>.withTag({Material: "iron"}));
Blacklist.addRecipe(<liquid:iron>, <tconstruct:pick_head>.withTag({Material: "iron"}));
Blacklist.addRecipe(<liquid:iron>, <tconstruct:tool_rod>.withTag({Material: "iron"}));
Blacklist.addRecipe(<liquid:iron>, <tconstruct:tough_tool_rod>.withTag({Material: "iron"}));
Blacklist.addRecipe(<liquid:iron>, <tconstruct:axe_head>.withTag({Material: "iron"}));
Blacklist.addRecipe(<liquid:iron>, <tconstruct:shovel_head>.withTag({Material: "iron"}));
Blacklist.addRecipe(<liquid:iridium>, <thermalfoundation:storage:7>);
Blacklist.addRecipe(<liquid:iridium>, <thermalfoundation:ore:7>);
Blacklist.addRecipe(<liquid:iridium>, <thermalfoundation:material:71>);
Blacklist.addRecipe(<liquid:iridium>, <thermalfoundation:material:135>);
Blacklist.addRecipe(<liquid:iridium>, <thermalfoundation:material:199>);
Blacklist.addRecipe(<liquid:iridium>, <thermalfoundation:material:263>);
Blacklist.addRecipe(<liquid:iridium>, <thermalfoundation:material:327>);
Blacklist.addRecipe(<liquid:obsidian>, <tconstruct:pick_head>.withTag({Material: "obsidian"}));
Blacklist.addRecipe(<liquid:obsidian>, <tconstruct:shovel_head>.withTag({Material: "obsidian"}));
Blacklist.addRecipe(<liquid:obsidian>, <tconstruct:axe_head>.withTag({Material: "obsidian"}));
Blacklist.addRecipe(<liquid:obsidian>, <tconstruct:broad_axe_head>.withTag({Material: "obsidian"}));
Blacklist.addRecipe(<liquid:obsidian>, <tconstruct:sword_blade>.withTag({Material: "obsidian"}));
Blacklist.addRecipe(<liquid:obsidian>, <tconstruct:large_sword_blade>.withTag({Material: "obsidian"}));
Blacklist.addRecipe(<liquid:obsidian>, <tconstruct:hammer_head>.withTag({Material: "obsidian"}));
Blacklist.addRecipe(<liquid:obsidian>, <tconstruct:excavator_head>.withTag({Material: "obsidian"}));
Blacklist.addRecipe(<liquid:obsidian>, <tconstruct:kama_head>.withTag({Material: "obsidian"}));
Blacklist.addRecipe(<liquid:obsidian>, <tconstruct:scythe_head>.withTag({Material: "obsidian"}));
Blacklist.addRecipe(<liquid:obsidian>, <tconstruct:pan_head>.withTag({Material: "obsidian"}));
Blacklist.addRecipe(<liquid:obsidian>, <tconstruct:sign_head>.withTag({Material: "obsidian"}));
Blacklist.addRecipe(<liquid:obsidian>, <tconstruct:tool_rod>.withTag({Material: "obsidian"}));
Blacklist.addRecipe(<liquid:obsidian>, <tconstruct:tough_tool_rod>.withTag({Material: "obsidian"}));
Blacklist.addRecipe(<liquid:obsidian>, <tconstruct:binding>.withTag({Material: "obsidian"}));
Blacklist.addRecipe(<liquid:obsidian>, <tconstruct:tough_binding>.withTag({Material: "obsidian"}));
Blacklist.addRecipe(<liquid:obsidian>, <tconstruct:wide_guard>.withTag({Material: "obsidian"}));
Blacklist.addRecipe(<liquid:obsidian>, <tconstruct:hand_guard>.withTag({Material: "obsidian"}));
Blacklist.addRecipe(<liquid:obsidian>, <tconstruct:cross_guard>.withTag({Material: "obsidian"}));
Blacklist.addRecipe(<liquid:obsidian>, <tconstruct:large_plate>.withTag({Material: "obsidian"}));
Blacklist.addRecipe(<liquid:obsidian>, <tconstruct:knife_blade>.withTag({Material: "obsidian"}));
Blacklist.addRecipe(<liquid:obsidian>, <tconstruct:bow_limb>.withTag({Material: "obsidian"}));
Blacklist.addRecipe(<liquid:obsidian>, <tconstruct:arrow_head>.withTag({Material: "obsidian"}));
Blacklist.addRecipe(<liquid:obsidian>, <tconstruct:sharpening_kit>.withTag({Material: "obsidian"}));
Blacklist.addRecipe(<liquid:pigiron>, <tconstruct:pan_head>.withTag({Material: "pigiron"}));
Blacklist.addRecipe(<liquid:pigiron>, <tconstruct:scythe_head>.withTag({Material: "pigiron"}));
Blacklist.addRecipe(<liquid:pigiron>, <tconstruct:kama_head>.withTag({Material: "pigiron"}));
Blacklist.addRecipe(<liquid:pigiron>, <tconstruct:excavator_head>.withTag({Material: "pigiron"}));
Blacklist.addRecipe(<liquid:pigiron>, <tconstruct:hammer_head>.withTag({Material: "pigiron"}));
Blacklist.addRecipe(<liquid:pigiron>, <tconstruct:large_sword_blade>.withTag({Material: "pigiron"}));
Blacklist.addRecipe(<liquid:pigiron>, <tconstruct:sword_blade>.withTag({Material: "pigiron"}));
Blacklist.addRecipe(<liquid:pigiron>, <tconstruct:cross_guard>.withTag({Material: "pigiron"}));
Blacklist.addRecipe(<liquid:pigiron>, <tconstruct:wide_guard>.withTag({Material: "pigiron"}));
Blacklist.addRecipe(<liquid:pigiron>, <tconstruct:broad_axe_head>.withTag({Material: "pigiron"}));
Blacklist.addRecipe(<liquid:pigiron>, <tconstruct:tough_tool_rod>.withTag({Material: "pigiron"}));
Blacklist.addRecipe(<liquid:pigiron>, <tconstruct:binding>.withTag({Material: "pigiron"}));
Blacklist.addRecipe(<liquid:pigiron>, <tconstruct:tough_binding>.withTag({Material: "pigiron"}));
Blacklist.addRecipe(<liquid:pigiron>, <tconstruct:hand_guard>.withTag({Material: "pigiron"}));
Blacklist.addRecipe(<liquid:pigiron>, <tconstruct:large_plate>.withTag({Material: "pigiron"}));
Blacklist.addRecipe(<liquid:pigiron>, <tconstruct:knife_blade>.withTag({Material: "pigiron"}));
Blacklist.addRecipe(<liquid:pigiron>, <tconstruct:bow_limb>.withTag({Material: "pigiron"}));
Blacklist.addRecipe(<liquid:pigiron>, <tconstruct:arrow_head>.withTag({Material: "pigiron"}));
Blacklist.addRecipe(<liquid:pigiron>, <tconstruct:sharpening_kit>.withTag({Material: "pigiron"}));
Blacklist.addRecipe(<liquid:pigiron>, <tconstruct:sign_head>.withTag({Material: "pigiron"}));
Blacklist.addRecipe(<liquid:pigiron>, <tconstruct:tool_rod>.withTag({Material: "pigiron"}));
Blacklist.addRecipe(<liquid:pigiron>, <tconstruct:axe_head>.withTag({Material: "pigiron"}));
Blacklist.addRecipe(<liquid:pigiron>, <tconstruct:shovel_head>.withTag({Material: "pigiron"}));
Blacklist.addRecipe(<liquid:pigiron>, <tconstruct:pick_head>.withTag({Material: "pigiron"}));
Blacklist.addRecipe(<liquid:steel>, <tconstruct:shard>.withTag({Material: "steel"}));
Blacklist.addRecipe(<liquid:steel>, <tconstruct:sharpening_kit>.withTag({Material: "steel"}));
Blacklist.addRecipe(<liquid:steel>, <tconstruct:pick_head>.withTag({Material: "steel"}));
Blacklist.addRecipe(<liquid:steel>, <tconstruct:shovel_head>.withTag({Material: "steel"}));
Blacklist.addRecipe(<liquid:steel>, <tconstruct:axe_head>.withTag({Material: "steel"}));
Blacklist.addRecipe(<liquid:steel>, <tconstruct:broad_axe_head>.withTag({Material: "steel"}));
Blacklist.addRecipe(<liquid:steel>, <tconstruct:sword_blade>.withTag({Material: "steel"}));
Blacklist.addRecipe(<liquid:steel>, <tconstruct:large_sword_blade>.withTag({Material: "steel"}));
Blacklist.addRecipe(<liquid:steel>, <tconstruct:hammer_head>.withTag({Material: "steel"}));
Blacklist.addRecipe(<liquid:steel>, <tconstruct:excavator_head>.withTag({Material: "steel"}));
Blacklist.addRecipe(<liquid:steel>, <tconstruct:kama_head>.withTag({Material: "steel"}));
Blacklist.addRecipe(<liquid:steel>, <tconstruct:scythe_head>.withTag({Material: "steel"}));
Blacklist.addRecipe(<liquid:steel>, <tconstruct:pan_head>.withTag({Material: "steel"}));
Blacklist.addRecipe(<liquid:steel>, <tconstruct:sign_head>.withTag({Material: "steel"}));
Blacklist.addRecipe(<liquid:steel>, <tconstruct:tool_rod>.withTag({Material: "steel"}));
Blacklist.addRecipe(<liquid:steel>, <tconstruct:tough_tool_rod>.withTag({Material: "steel"}));
Blacklist.addRecipe(<liquid:steel>, <tconstruct:binding>.withTag({Material: "steel"}));
Blacklist.addRecipe(<liquid:steel>, <tconstruct:tough_binding>.withTag({Material: "steel"}));
Blacklist.addRecipe(<liquid:steel>, <tconstruct:wide_guard>.withTag({Material: "steel"}));
Blacklist.addRecipe(<liquid:steel>, <tconstruct:hand_guard>.withTag({Material: "steel"}));
Blacklist.addRecipe(<liquid:steel>, <tconstruct:cross_guard>.withTag({Material: "steel"}));
Blacklist.addRecipe(<liquid:steel>, <tconstruct:large_plate>.withTag({Material: "steel"}));
Blacklist.addRecipe(<liquid:steel>, <tconstruct:knife_blade>.withTag({Material: "steel"}));
Blacklist.addRecipe(<liquid:steel>, <tconstruct:bow_limb>.withTag({Material: "steel"}));
Blacklist.addRecipe(<liquid:steel>, <tconstruct:arrow_head>.withTag({Material: "steel"}));
Blacklist.addRecipe(<liquid:steel>, <tcomplement:sledge_head>.withTag({Material: "steel"}));
Blacklist.addRecipe(<liquid:steel>, <thermalfoundation:material:352>);
Blacklist.addRecipe(<liquid:steel>, <thermalfoundation:material:288>);
Blacklist.addRecipe(<liquid:steel>, <thermalfoundation:material:224>);
Blacklist.addRecipe(<liquid:steel>, <thermalfoundation:material:96>);
Blacklist.addRecipe(<liquid:steel>, <thermalfoundation:material:160>);
Blacklist.addRecipe(<liquid:steel>, <thermalfoundation:storage_alloy>);
Blacklist.addRecipe(<liquid:steel>, <thermalfoundation:tool.sickle_steel>);
Blacklist.addRecipe(<liquid:steel>, <thermalfoundation:tool.bow_steel>);
Blacklist.addRecipe(<liquid:steel>, <thermalfoundation:armor.boots_steel>);
Blacklist.addRecipe(<liquid:steel>, <thermalfoundation:armor.legs_steel>);
Blacklist.addRecipe(<liquid:steel>, <thermalfoundation:armor.plate_steel>);
Blacklist.addRecipe(<liquid:steel>, <thermalfoundation:armor.helmet_steel>);
Blacklist.addRecipe(<liquid:steel>, <thermalfoundation:tool.sickle_steel>);
Blacklist.addRecipe(<liquid:steel>, <thermalfoundation:tool.hoe_steel>);
Blacklist.addRecipe(<liquid:steel>, <thermalfoundation:tool.sword_steel>);
Blacklist.addRecipe(<liquid:steel>, <tcomplement:steel_helmet>);
Blacklist.addRecipe(<liquid:steel>, <tcomplement:steel_chestplate>);
Blacklist.addRecipe(<liquid:steel>, <tcomplement:steel_leggings>);
Blacklist.addRecipe(<liquid:steel>, <tcomplement:steel_boots>);
Blacklist.addRecipe(<liquid:cobalt>, <tconstruct:shard>.withTag({Material: "cobalt"}));
Blacklist.addRecipe(<liquid:cobalt>, <tconstruct:sharpening_kit>.withTag({Material: "cobalt"}));
Blacklist.addRecipe(<liquid:cobalt>, <tconstruct:pick_head>.withTag({Material: "cobalt"}));
Blacklist.addRecipe(<liquid:cobalt>, <tconstruct:shovel_head>.withTag({Material: "cobalt"}));
Blacklist.addRecipe(<liquid:cobalt>, <tconstruct:axe_head>.withTag({Material: "cobalt"}));
Blacklist.addRecipe(<liquid:cobalt>, <tconstruct:broad_axe_head>.withTag({Material: "cobalt"}));
Blacklist.addRecipe(<liquid:cobalt>, <tconstruct:sword_blade>.withTag({Material: "cobalt"}));
Blacklist.addRecipe(<liquid:cobalt>, <tconstruct:large_sword_blade>.withTag({Material: "cobalt"}));
Blacklist.addRecipe(<liquid:cobalt>, <tconstruct:hammer_head>.withTag({Material: "cobalt"}));
Blacklist.addRecipe(<liquid:cobalt>, <tconstruct:excavator_head>.withTag({Material: "cobalt"}));
Blacklist.addRecipe(<liquid:cobalt>, <tconstruct:kama_head>.withTag({Material: "cobalt"}));
Blacklist.addRecipe(<liquid:cobalt>, <tconstruct:scythe_head>.withTag({Material: "cobalt"}));
Blacklist.addRecipe(<liquid:cobalt>, <tconstruct:pan_head>.withTag({Material: "cobalt"}));
Blacklist.addRecipe(<liquid:cobalt>, <tconstruct:sign_head>.withTag({Material: "cobalt"}));
Blacklist.addRecipe(<liquid:cobalt>, <tconstruct:tool_rod>.withTag({Material: "cobalt"}));
Blacklist.addRecipe(<liquid:cobalt>, <tconstruct:tough_tool_rod>.withTag({Material: "cobalt"}));
Blacklist.addRecipe(<liquid:cobalt>, <tconstruct:binding>.withTag({Material: "cobalt"}));
Blacklist.addRecipe(<liquid:cobalt>, <tconstruct:tough_binding>.withTag({Material: "cobalt"}));
Blacklist.addRecipe(<liquid:cobalt>, <tconstruct:wide_guard>.withTag({Material: "cobalt"}));
Blacklist.addRecipe(<liquid:cobalt>, <tconstruct:hand_guard>.withTag({Material: "cobalt"}));
Blacklist.addRecipe(<liquid:cobalt>, <tconstruct:cross_guard>.withTag({Material: "cobalt"}));
Blacklist.addRecipe(<liquid:cobalt>, <tconstruct:large_plate>.withTag({Material: "cobalt"}));
Blacklist.addRecipe(<liquid:cobalt>, <tconstruct:knife_blade>.withTag({Material: "cobalt"}));
Blacklist.addRecipe(<liquid:cobalt>, <tconstruct:bow_limb>.withTag({Material: "cobalt"}));
Blacklist.addRecipe(<liquid:cobalt>, <tconstruct:arrow_head>.withTag({Material: "cobalt"}));
Blacklist.addRecipe(<liquid:ardite>, <tconstruct:shard>.withTag({Material: "ardite"}));
Blacklist.addRecipe(<liquid:ardite>, <tconstruct:sharpening_kit>.withTag({Material: "ardite"}));
Blacklist.addRecipe(<liquid:ardite>, <tconstruct:pick_head>.withTag({Material: "ardite"}));
Blacklist.addRecipe(<liquid:ardite>, <tconstruct:shovel_head>.withTag({Material: "ardite"}));
Blacklist.addRecipe(<liquid:ardite>, <tconstruct:axe_head>.withTag({Material: "ardite"}));
Blacklist.addRecipe(<liquid:ardite>, <tconstruct:broad_axe_head>.withTag({Material: "ardite"}));
Blacklist.addRecipe(<liquid:ardite>, <tconstruct:sword_blade>.withTag({Material: "ardite"}));
Blacklist.addRecipe(<liquid:ardite>, <tconstruct:large_sword_blade>.withTag({Material: "ardite"}));
Blacklist.addRecipe(<liquid:ardite>, <tconstruct:hammer_head>.withTag({Material: "ardite"}));
Blacklist.addRecipe(<liquid:ardite>, <tconstruct:excavator_head>.withTag({Material: "ardite"}));
Blacklist.addRecipe(<liquid:ardite>, <tconstruct:kama_head>.withTag({Material: "ardite"}));
Blacklist.addRecipe(<liquid:ardite>, <tconstruct:scythe_head>.withTag({Material: "ardite"}));
Blacklist.addRecipe(<liquid:ardite>, <tconstruct:pan_head>.withTag({Material: "ardite"}));
Blacklist.addRecipe(<liquid:ardite>, <tconstruct:sign_head>.withTag({Material: "ardite"}));
Blacklist.addRecipe(<liquid:ardite>, <tconstruct:tool_rod>.withTag({Material: "ardite"}));
Blacklist.addRecipe(<liquid:ardite>, <tconstruct:tough_tool_rod>.withTag({Material: "ardite"}));
Blacklist.addRecipe(<liquid:ardite>, <tconstruct:binding>.withTag({Material: "ardite"}));
Blacklist.addRecipe(<liquid:ardite>, <tconstruct:tough_binding>.withTag({Material: "ardite"}));
Blacklist.addRecipe(<liquid:ardite>, <tconstruct:wide_guard>.withTag({Material: "ardite"}));
Blacklist.addRecipe(<liquid:ardite>, <tconstruct:hand_guard>.withTag({Material: "ardite"}));
Blacklist.addRecipe(<liquid:ardite>, <tconstruct:cross_guard>.withTag({Material: "ardite"}));
Blacklist.addRecipe(<liquid:ardite>, <tconstruct:large_plate>.withTag({Material: "ardite"}));
Blacklist.addRecipe(<liquid:ardite>, <tconstruct:knife_blade>.withTag({Material: "ardite"}));
Blacklist.addRecipe(<liquid:ardite>, <tconstruct:bow_limb>.withTag({Material: "ardite"}));
Blacklist.addRecipe(<liquid:ardite>, <tconstruct:arrow_head>.withTag({Material: "ardite"}));
Blacklist.addRecipe(<liquid:manyullyn>, <tconstruct:shard>.withTag({Material: "manyullyn"}));
Blacklist.addRecipe(<liquid:manyullyn>, <tconstruct:sharpening_kit>.withTag({Material: "manyullyn"}));
Blacklist.addRecipe(<liquid:manyullyn>, <tconstruct:pick_head>.withTag({Material: "manyullyn"}));
Blacklist.addRecipe(<liquid:manyullyn>, <tconstruct:shovel_head>.withTag({Material: "manyullyn"}));
Blacklist.addRecipe(<liquid:manyullyn>, <tconstruct:axe_head>.withTag({Material: "manyullyn"}));
Blacklist.addRecipe(<liquid:manyullyn>, <tconstruct:broad_axe_head>.withTag({Material: "manyullyn"}));
Blacklist.addRecipe(<liquid:manyullyn>, <tconstruct:sword_blade>.withTag({Material: "manyullyn"}));
Blacklist.addRecipe(<liquid:manyullyn>, <tconstruct:large_sword_blade>.withTag({Material: "manyullyn"}));
Blacklist.addRecipe(<liquid:manyullyn>, <tconstruct:hammer_head>.withTag({Material: "manyullyn"}));
Blacklist.addRecipe(<liquid:manyullyn>, <tconstruct:excavator_head>.withTag({Material: "manyullyn"}));
Blacklist.addRecipe(<liquid:manyullyn>, <tconstruct:kama_head>.withTag({Material: "manyullyn"}));
Blacklist.addRecipe(<liquid:manyullyn>, <tconstruct:scythe_head>.withTag({Material: "manyullyn"}));
Blacklist.addRecipe(<liquid:manyullyn>, <tconstruct:pan_head>.withTag({Material: "manyullyn"}));
Blacklist.addRecipe(<liquid:manyullyn>, <tconstruct:sign_head>.withTag({Material: "manyullyn"}));
Blacklist.addRecipe(<liquid:manyullyn>, <tconstruct:tool_rod>.withTag({Material: "manyullyn"}));
Blacklist.addRecipe(<liquid:manyullyn>, <tconstruct:tough_tool_rod>.withTag({Material: "manyullyn"}));
Blacklist.addRecipe(<liquid:manyullyn>, <tconstruct:binding>.withTag({Material: "manyullyn"}));
Blacklist.addRecipe(<liquid:manyullyn>, <tconstruct:tough_binding>.withTag({Material: "manyullyn"}));
Blacklist.addRecipe(<liquid:manyullyn>, <tconstruct:wide_guard>.withTag({Material: "manyullyn"}));
Blacklist.addRecipe(<liquid:manyullyn>, <tconstruct:hand_guard>.withTag({Material: "manyullyn"}));
Blacklist.addRecipe(<liquid:manyullyn>, <tconstruct:cross_guard>.withTag({Material: "manyullyn"}));
Blacklist.addRecipe(<liquid:manyullyn>, <tconstruct:large_plate>.withTag({Material: "manyullyn"}));
Blacklist.addRecipe(<liquid:manyullyn>, <tconstruct:knife_blade>.withTag({Material: "manyullyn"}));
Blacklist.addRecipe(<liquid:manyullyn>, <tconstruct:bow_limb>.withTag({Material: "manyullyn"}));
Blacklist.addRecipe(<liquid:manyullyn>, <tconstruct:arrow_head>.withTag({Material: "manyullyn"}));
Blacklist.addRecipe(<liquid:manyullyn>, <tcomplement:manyullyn_helmet>);
Blacklist.addRecipe(<liquid:manyullyn>, <tcomplement:manyullyn_chestplate>);
Blacklist.addRecipe(<liquid:manyullyn>, <tcomplement:manyullyn_leggings>);
Blacklist.addRecipe(<liquid:manyullyn>, <tcomplement:manyullyn_boots>);
Blacklist.addRecipe(<liquid:manyullyn>, <tconstruct:nuggets:2>);
Blacklist.addRecipe(<liquid:manyullyn>, <tconstruct:ingots:2>);
Blacklist.addRecipe(<liquid:manyullyn>, <tconstruct:metal:2>);
Blacklist.addRecipe(<liquid:manyullyn>, <tcomplement:sledge_head>.withTag({Material: "manyullyn"}));
Blacklist.addRecipe(<liquid:electrum>, <tconstruct:shard>.withTag({Material: "electrum"}));
Blacklist.addRecipe(<liquid:electrum>, <tconstruct:sharpening_kit>.withTag({Material: "electrum"}));
Blacklist.addRecipe(<liquid:electrum>, <tconstruct:pick_head>.withTag({Material: "electrum"}));
Blacklist.addRecipe(<liquid:electrum>, <tconstruct:shovel_head>.withTag({Material: "electrum"}));
Blacklist.addRecipe(<liquid:electrum>, <tconstruct:axe_head>.withTag({Material: "electrum"}));
Blacklist.addRecipe(<liquid:electrum>, <tconstruct:broad_axe_head>.withTag({Material: "electrum"}));
Blacklist.addRecipe(<liquid:electrum>, <tconstruct:sword_blade>.withTag({Material: "electrum"}));
Blacklist.addRecipe(<liquid:electrum>, <tconstruct:large_sword_blade>.withTag({Material: "electrum"}));
Blacklist.addRecipe(<liquid:electrum>, <tconstruct:hammer_head>.withTag({Material: "electrum"}));
Blacklist.addRecipe(<liquid:electrum>, <tconstruct:excavator_head>.withTag({Material: "electrum"}));
Blacklist.addRecipe(<liquid:electrum>, <tconstruct:kama_head>.withTag({Material: "electrum"}));
Blacklist.addRecipe(<liquid:electrum>, <tconstruct:scythe_head>.withTag({Material: "electrum"}));
Blacklist.addRecipe(<liquid:electrum>, <tconstruct:pan_head>.withTag({Material: "electrum"}));
Blacklist.addRecipe(<liquid:electrum>, <tconstruct:sign_head>.withTag({Material: "electrum"}));
Blacklist.addRecipe(<liquid:electrum>, <tconstruct:tool_rod>.withTag({Material: "electrum"}));
Blacklist.addRecipe(<liquid:electrum>, <tconstruct:tough_tool_rod>.withTag({Material: "electrum"}));
Blacklist.addRecipe(<liquid:electrum>, <tconstruct:binding>.withTag({Material: "electrum"}));
Blacklist.addRecipe(<liquid:electrum>, <tconstruct:tough_binding>.withTag({Material: "electrum"}));
Blacklist.addRecipe(<liquid:electrum>, <tconstruct:wide_guard>.withTag({Material: "electrum"}));
Blacklist.addRecipe(<liquid:electrum>, <tconstruct:hand_guard>.withTag({Material: "electrum"}));
Blacklist.addRecipe(<liquid:electrum>, <tconstruct:cross_guard>.withTag({Material: "electrum"}));
Blacklist.addRecipe(<liquid:electrum>, <thermalfoundation:tool.sickle_electrum>);
Blacklist.addRecipe(<liquid:electrum>, <tcomplement:sledge_head>.withTag({Material: "electrum"}));
Blacklist.addRecipe(<liquid:electrum>, <thermalfoundation:material:97>);
Blacklist.addRecipe(<liquid:electrum>, <thermalfoundation:material:161>);
Blacklist.addRecipe(<liquid:electrum>, <thermalfoundation:material:225>);
Blacklist.addRecipe(<liquid:electrum>, <thermalfoundation:material:353>);
Blacklist.addRecipe(<liquid:electrum>, <thermalfoundation:material:289>);
Blacklist.addRecipe(<liquid:electrum>, <thermalfoundation:material:515>);
Blacklist.addRecipe(<liquid:electrum>, <thermalfoundation:armor.helmet_electrum>);
Blacklist.addRecipe(<liquid:electrum>, <thermalfoundation:armor.plate_electrum>);
Blacklist.addRecipe(<liquid:electrum>, <thermalfoundation:armor.legs_electrum>);
Blacklist.addRecipe(<liquid:electrum>, <thermalfoundation:armor.boots_electrum>);
Blacklist.addRecipe(<liquid:electrum>, <thermalfoundation:tool.bow_electrum>);
Blacklist.addRecipe(<liquid:electrum>, <thermalfoundation:tool.sickle_electrum>);
Blacklist.addRecipe(<liquid:electrum>, <thermalfoundation:storage_alloy:1>);
Blacklist.addRecipe(<liquid:electrum>, <tconstruct:large_plate>.withTag({Material: "electrum"}));
Blacklist.addRecipe(<liquid:electrum>, <tconstruct:knife_blade>.withTag({Material: "electrum"}));
Blacklist.addRecipe(<liquid:electrum>, <tconstruct:bow_limb>.withTag({Material: "electrum"}));
Blacklist.addRecipe(<liquid:electrum>, <tconstruct:arrow_head>.withTag({Material: "electrum"}));
Blacklist.addRecipe(<liquid:silver>, <geolosys:cluster:4>);
Blacklist.addRecipe(<liquid:silver>, <thermalfoundation:tool.sickle_silver>);
Blacklist.addRecipe(<liquid:silver>, <thermalfoundation:material:66>);
Blacklist.addRecipe(<liquid:silver>, <thermalfoundation:material:130>);
Blacklist.addRecipe(<liquid:silver>, <thermalfoundation:material:194>);
Blacklist.addRecipe(<liquid:silver>, <thermalfoundation:material:258>);
Blacklist.addRecipe(<liquid:silver>, <thermalfoundation:material:322>);
Blacklist.addRecipe(<liquid:silver>, <thermalfoundation:armor.helmet_silver>);
Blacklist.addRecipe(<liquid:silver>, <thermalfoundation:armor.plate_silver>);
Blacklist.addRecipe(<liquid:silver>, <thermalfoundation:armor.legs_silver>);
Blacklist.addRecipe(<liquid:silver>, <thermalfoundation:armor.boots_silver>);
Blacklist.addRecipe(<liquid:silver>, <thermalfoundation:tool.bow_silver>);
Blacklist.addRecipe(<liquid:silver>, <thermalfoundation:tool.sickle_silver>);
Blacklist.addRecipe(<liquid:silver>, <thermalfoundation:storage:2>);
Blacklist.addRecipe(<liquid:silver>, <tconstruct:shard>.withTag({Material: "silver"}));
Blacklist.addRecipe(<liquid:silver>, <tconstruct:pick_head>.withTag({Material: "silver"}));
Blacklist.addRecipe(<liquid:silver>, <tconstruct:sharpening_kit>.withTag({Material: "silver"}));
Blacklist.addRecipe(<liquid:silver>, <tconstruct:shovel_head>.withTag({Material: "silver"}));
Blacklist.addRecipe(<liquid:silver>, <tconstruct:axe_head>.withTag({Material: "silver"}));
Blacklist.addRecipe(<liquid:silver>, <tconstruct:broad_axe_head>.withTag({Material: "silver"}));
Blacklist.addRecipe(<liquid:silver>, <tconstruct:sword_blade>.withTag({Material: "silver"}));
Blacklist.addRecipe(<liquid:silver>, <tconstruct:large_sword_blade>.withTag({Material: "silver"}));
Blacklist.addRecipe(<liquid:silver>, <tconstruct:hammer_head>.withTag({Material: "silver"}));
Blacklist.addRecipe(<liquid:silver>, <tconstruct:excavator_head>.withTag({Material: "silver"}));
Blacklist.addRecipe(<liquid:silver>, <tconstruct:kama_head>.withTag({Material: "silver"}));
Blacklist.addRecipe(<liquid:silver>, <tconstruct:scythe_head>.withTag({Material: "silver"}));
Blacklist.addRecipe(<liquid:silver>, <tconstruct:pan_head>.withTag({Material: "silver"}));
Blacklist.addRecipe(<liquid:silver>, <tconstruct:sign_head>.withTag({Material: "silver"}));
Blacklist.addRecipe(<liquid:silver>, <tconstruct:tool_rod>.withTag({Material: "silver"}));
Blacklist.addRecipe(<liquid:silver>, <tconstruct:tough_tool_rod>.withTag({Material: "silver"}));
Blacklist.addRecipe(<liquid:silver>, <tconstruct:binding>.withTag({Material: "silver"}));
Blacklist.addRecipe(<liquid:silver>, <tconstruct:tough_binding>.withTag({Material: "silver"}));
Blacklist.addRecipe(<liquid:silver>, <tconstruct:wide_guard>.withTag({Material: "silver"}));
Blacklist.addRecipe(<liquid:silver>, <tconstruct:hand_guard>.withTag({Material: "silver"}));
Blacklist.addRecipe(<liquid:silver>, <tconstruct:cross_guard>.withTag({Material: "silver"}));
Blacklist.addRecipe(<liquid:silver>, <tconstruct:large_plate>.withTag({Material: "silver"}));
Blacklist.addRecipe(<liquid:silver>, <tconstruct:knife_blade>.withTag({Material: "silver"}));
Blacklist.addRecipe(<liquid:silver>, <tconstruct:bow_limb>.withTag({Material: "silver"}));
Blacklist.addRecipe(<liquid:silver>, <tconstruct:arrow_head>.withTag({Material: "silver"}));
Blacklist.addRecipe(<liquid:silver>, <thermalfoundation:ore:2>);
Blacklist.addRecipe(<liquid:silver>, <tcomplement:sledge_head>.withTag({Material: "silver"}));
Blacklist.addRecipe(<liquid:silver>, <exnihilocreatio:item_ore_silver:1>);
Blacklist.addRecipe(<liquid:silver>, <exnihilocreatio:item_ore_silver:2>);
Blacklist.addRecipe(<liquid:silver>, <mysticalworld:silver_dust_tiny>);
Blacklist.addRecipe(<liquid:silver>, <iceandfire:silverpile>);
Blacklist.addRecipe(<liquid:silver>, <iceandfire:silver_sword>);
Blacklist.addRecipe(<liquid:silver>, <iceandfire:silver_axe>);
Blacklist.addRecipe(<liquid:silver>, <iceandfire:silver_shovel>);
Blacklist.addRecipe(<liquid:silver>, <iceandfire:silver_pickaxe>);
Blacklist.addRecipe(<liquid:silver>, <iceandfire:silver_hoe>);
Blacklist.addRecipe(<liquid:silver>, <iceandfire:armor_silver_metal_helmet>);
Blacklist.addRecipe(<liquid:silver>, <iceandfire:armor_silver_metal_chestplate>);
Blacklist.addRecipe(<liquid:silver>, <iceandfire:armor_silver_metal_leggings>);
Blacklist.addRecipe(<liquid:silver>, <iceandfire:armor_silver_metal_boots>);
Blacklist.addRecipe(<liquid:silver>, <iceandfire:dragonarmor_silver>);
Blacklist.addRecipe(<liquid:silver>, <iceandfire:dragonarmor_silver:1>);
Blacklist.addRecipe(<liquid:silver>, <iceandfire:dragonarmor_silver:2>);
Blacklist.addRecipe(<liquid:silver>, <iceandfire:dragonarmor_silver:3>);
Blacklist.addRecipe(<liquid:silver>, <thermalfoundation:material:514>);
Blacklist.addRecipe(<liquid:lead>, <tconstruct:shard>.withTag({Material: "lead"}));
Blacklist.addRecipe(<liquid:lead>, <tconstruct:sharpening_kit>.withTag({Material: "lead"}));
Blacklist.addRecipe(<liquid:lead>, <tconstruct:pick_head>.withTag({Material: "lead"}));
Blacklist.addRecipe(<liquid:lead>, <geolosys:cluster:5>);
Blacklist.addRecipe(<liquid:lead>, <thermalfoundation:tool.sickle_lead>);
Blacklist.addRecipe(<liquid:lead>, <thermalfoundation:storage:3>);
Blacklist.addRecipe(<liquid:lead>, <thermalfoundation:material:67>);
Blacklist.addRecipe(<liquid:lead>, <thermalfoundation:material:131>);
Blacklist.addRecipe(<liquid:lead>, <thermalfoundation:material:195>);
Blacklist.addRecipe(<liquid:lead>, <thermalfoundation:material:259>);
Blacklist.addRecipe(<liquid:lead>, <thermalfoundation:material:323>);
Blacklist.addRecipe(<liquid:lead>, <thermalfoundation:armor.helmet_lead>);
Blacklist.addRecipe(<liquid:lead>, <thermalfoundation:armor.plate_lead>);
Blacklist.addRecipe(<liquid:lead>, <thermalfoundation:armor.legs_lead>);
Blacklist.addRecipe(<liquid:lead>, <thermalfoundation:armor.boots_lead>);
Blacklist.addRecipe(<liquid:lead>, <thermalfoundation:tool.bow_lead>);
Blacklist.addRecipe(<liquid:lead>, <thermalfoundation:tool.sickle_lead>);
Blacklist.addRecipe(<liquid:lead>, <thermalfoundation:tool.sword_lead>);
Blacklist.addRecipe(<liquid:lead>, <thermalfoundation:tool.hoe_lead>);
Blacklist.addRecipe(<liquid:lead>, <tconstruct:shovel_head>.withTag({Material: "lead"}));
Blacklist.addRecipe(<liquid:lead>, <tconstruct:axe_head>.withTag({Material: "lead"}));
Blacklist.addRecipe(<liquid:lead>, <tconstruct:broad_axe_head>.withTag({Material: "lead"}));
Blacklist.addRecipe(<liquid:lead>, <tconstruct:sword_blade>.withTag({Material: "lead"}));
Blacklist.addRecipe(<liquid:lead>, <tconstruct:large_sword_blade>.withTag({Material: "lead"}));
Blacklist.addRecipe(<liquid:lead>, <tconstruct:hammer_head>.withTag({Material: "lead"}));
Blacklist.addRecipe(<liquid:lead>, <tconstruct:excavator_head>.withTag({Material: "lead"}));
Blacklist.addRecipe(<liquid:lead>, <tconstruct:kama_head>.withTag({Material: "lead"}));
Blacklist.addRecipe(<liquid:lead>, <tconstruct:scythe_head>.withTag({Material: "lead"}));
Blacklist.addRecipe(<liquid:lead>, <tconstruct:pan_head>.withTag({Material: "lead"}));
Blacklist.addRecipe(<liquid:lead>, <tconstruct:sign_head>.withTag({Material: "lead"}));
Blacklist.addRecipe(<liquid:lead>, <tconstruct:tool_rod>.withTag({Material: "lead"}));
Blacklist.addRecipe(<liquid:lead>, <tconstruct:tough_tool_rod>.withTag({Material: "lead"}));
Blacklist.addRecipe(<liquid:lead>, <tconstruct:binding>.withTag({Material: "lead"}));
Blacklist.addRecipe(<liquid:lead>, <thermalfoundation:ore:3>);
Blacklist.addRecipe(<liquid:lead>, <exnihilocreatio:item_ore_lead:1>);
Blacklist.addRecipe(<liquid:lead>, <exnihilocreatio:item_ore_lead:2>);
Blacklist.addRecipe(<liquid:lead>, <tcomplement:sledge_head>.withTag({Material: "lead"}));
Blacklist.addRecipe(<liquid:lead>, <tconstruct:tough_binding>.withTag({Material: "lead"}));
Blacklist.addRecipe(<liquid:lead>, <tconstruct:wide_guard>.withTag({Material: "lead"}));
Blacklist.addRecipe(<liquid:lead>, <tconstruct:hand_guard>.withTag({Material: "lead"}));
Blacklist.addRecipe(<liquid:lead>, <tconstruct:cross_guard>.withTag({Material: "lead"}));
Blacklist.addRecipe(<liquid:lead>, <tconstruct:large_plate>.withTag({Material: "lead"}));
Blacklist.addRecipe(<liquid:lead>, <tconstruct:knife_blade>.withTag({Material: "lead"}));
Blacklist.addRecipe(<liquid:lead>, <tconstruct:bow_limb>.withTag({Material: "lead"}));
Blacklist.addRecipe(<liquid:lead>, <tconstruct:arrow_head>.withTag({Material: "lead"}));
Blacklist.addRecipe(<liquid:platinum>, <geolosys:cluster:8>);
Blacklist.addRecipe(<liquid:platinum>, <thermalfoundation:material:134>);
Blacklist.addRecipe(<liquid:platinum>, <thermalfoundation:material:198>);
Blacklist.addRecipe(<liquid:platinum>, <thermalfoundation:material:262>);
Blacklist.addRecipe(<liquid:platinum>, <thermalfoundation:material:326>);
Blacklist.addRecipe(<liquid:platinum>, <thermalfoundation:armor.helmet_platinum>);
Blacklist.addRecipe(<liquid:platinum>, <thermalfoundation:armor.plate_platinum>);
Blacklist.addRecipe(<liquid:platinum>, <thermalfoundation:armor.legs_platinum>);
Blacklist.addRecipe(<liquid:platinum>, <thermalfoundation:armor.boots_platinum>);
Blacklist.addRecipe(<liquid:platinum>, <thermalfoundation:storage:6>);
Blacklist.addRecipe(<liquid:platinum>, <exnihilocreatio:item_ore_platinum:1>);
Blacklist.addRecipe(<liquid:platinum>, <thermalfoundation:ore:6>);
Blacklist.addRecipe(<liquid:platinum>, <thermalfoundation:tool.sickle_platinum>);
Blacklist.addRecipe(<liquid:platinum>, <thermalfoundation:material:70>);
Blacklist.addRecipe(<liquid:platinum>, <thermalfoundation:tool.bow_platinum>);
Blacklist.addRecipe(<liquid:platinum>, <exnihilocreatio:item_ore_platinum:2>);
Blacklist.addRecipe(<liquid:cobalt>, <tconstruct:ore>);
Blacklist.addRecipe(<liquid:ardite>, <tconstruct:ore:1>);
Blacklist.addRecipe(<liquid:obsidian>, <minecraft:obsidian>);
Blacklist.addRecipe(<liquid:emerald>, <minecraft:emerald_ore>);
Blacklist.addRecipe(<liquid:emerald>, <minecraft:emerald>);
Blacklist.addRecipe(<liquid:emerald>, <minecraft:emerald_block>);
Blacklist.addRecipe(<liquid:obsidian>, <tcomplement:sledge_head>.withTag({Material: "obsidian"}));
Blacklist.addRecipe(<liquid:pigiron>, <tcomplement:sledge_head>.withTag({Material: "pigiron"}));
Blacklist.addRecipe(<liquid:knightslime>, <tcomplement:sledge_head>.withTag({Material: "knightslime"}));
Blacklist.addRecipe(<liquid:knightslime>, <tconstruct:nuggets:3>);
Blacklist.addRecipe(<liquid:knightslime>, <tconstruct:ingots:3>);
Blacklist.addRecipe(<liquid:knightslime>, <tconstruct:metal:3>);
Blacklist.addRecipe(<liquid:knightslime>, <tcomplement:knightslime_boots>);
Blacklist.addRecipe(<liquid:knightslime>, <tcomplement:knightslime_leggings>);
Blacklist.addRecipe(<liquid:knightslime>, <tcomplement:knightslime_chestplate>);
Blacklist.addRecipe(<liquid:knightslime>, <tcomplement:knightslime_helmet>);
Blacklist.addRecipe(<liquid:cobalt>, <tcomplement:sledge_head>.withTag({Material: "cobalt"}));
Blacklist.addRecipe(<liquid:ardite>, <tcomplement:sledge_head>.withTag({Material: "ardite"}));
Blacklist.addRecipe(<liquid:pigiron>, <tconstruct:nuggets:4>);
Blacklist.addRecipe(<liquid:pigiron>, <tconstruct:ingots:4>);
Blacklist.addRecipe(<liquid:pigiron>, <tconstruct:metal:4>);
Blacklist.addRecipe(<liquid:cobalt>, <tconstruct:nuggets>);
Blacklist.addRecipe(<liquid:cobalt>, <tconstruct:ingots>);
Blacklist.addRecipe(<liquid:cobalt>, <tconstruct:metal>);
Blacklist.addRecipe(<liquid:ardite>, <tconstruct:nuggets:1>);
Blacklist.addRecipe(<liquid:ardite>, <tconstruct:ingots:1>);
Blacklist.addRecipe(<liquid:ardite>, <tconstruct:metal:1>);
Blacklist.addRecipe(<liquid:alubrass>, <tconstruct:metal:5>);
Blacklist.addRecipe(<liquid:alubrass>, <tconstruct:ingots:5>);
Blacklist.addRecipe(<liquid:alubrass>, <tconstruct:nuggets:5>);
Blacklist.addRecipe(<liquid:aluminum>, <thermalfoundation:storage:4>);
Blacklist.addRecipe(<liquid:aluminum>, <thermalfoundation:ore:4>);
Blacklist.addRecipe(<liquid:aluminum>, <thermalfoundation:material:68>);
Blacklist.addRecipe(<liquid:aluminum>, <thermalfoundation:material:132>);
Blacklist.addRecipe(<liquid:aluminum>, <thermalfoundation:material:196>);
Blacklist.addRecipe(<liquid:aluminum>, <thermalfoundation:material:260>);
Blacklist.addRecipe(<liquid:aluminum>, <thermalfoundation:material:324>);
Blacklist.addRecipe(<liquid:aluminum>, <thermalfoundation:armor.helmet_aluminum>);
Blacklist.addRecipe(<liquid:aluminum>, <thermalfoundation:armor.plate_aluminum>);
Blacklist.addRecipe(<liquid:aluminum>, <thermalfoundation:armor.legs_aluminum>);
Blacklist.addRecipe(<liquid:aluminum>, <thermalfoundation:armor.boots_aluminum>);
Blacklist.addRecipe(<liquid:aluminum>, <thermalfoundation:tool.sickle_aluminum>);
Blacklist.addRecipe(<liquid:aluminum>, <thermalfoundation:tool.bow_aluminum>);
Blacklist.addRecipe(<liquid:aluminum>, <thermalfoundation:ore:4>);
Blacklist.addRecipe(<liquid:aluminum>, <exnihilocreatio:item_ore_aluminium:1>);
Blacklist.addRecipe(<liquid:aluminum>, <exnihilocreatio:item_ore_aluminium:2>);
Blacklist.addRecipe(<liquid:aluminum>, <immersiveengineering:sheetmetal:1>);
Blacklist.addRecipe(<liquid:aluminum>, <immersiveengineering:material:3>);
Blacklist.addRecipe(<liquid:aluminum>, <immersiveengineering:faraday_suit_feet>);
Blacklist.addRecipe(<liquid:aluminum>, <techreborn:machine_frame>);
Blacklist.addRecipe(<liquid:aluminum>, <immersiveengineering:faraday_suit_legs>);
Blacklist.addRecipe(<liquid:aluminum>, <immersiveengineering:faraday_suit_chest>);
Blacklist.addRecipe(<liquid:aluminum>, <immersiveengineering:faraday_suit_head>);
Blacklist.addRecipe(<liquid:aluminum>, <techreborn:smalldust:1>);
Blacklist.addRecipe(<liquid:cobalt>, <exnihilocreatio:item_ore_cobalt:1>);
Blacklist.addRecipe(<liquid:ardite>, <exnihilocreatio:item_ore_ardite:1>);
Blacklist.addRecipe(<liquid:ardite>, <exnihilocreatio:item_ore_ardite:2>);
Blacklist.addRecipe(<liquid:cobalt>, <exnihilocreatio:item_ore_cobalt:2>);
Blacklist.addRecipe(<liquid:obsidian>, <adchimneys:obsidian>);
Blacklist.addRecipe(<liquid:emerald>, <adchimneys:emerald_block>);
Blacklist.addRecipe(<liquid:emerald>, <thermalfoundation:material:17>);
Blacklist.addRecipe(<liquid:emerald>, <thermalfoundation:material:27>);
Blacklist.addRecipe(<liquid:emerald>, <minecraft:emerald_ore>);
Blacklist.addRecipe(<liquid:nickel>, <thermalfoundation:tool.sickle_nickel>);
Blacklist.addRecipe(<liquid:nickel>, <geolosys:cluster:7>);
Blacklist.addRecipe(<liquid:nickel>, <thermalfoundation:ore:5>);
Blacklist.addRecipe(<liquid:nickel>, <exnihilocreatio:item_ore_nickel:1>);
Blacklist.addRecipe(<liquid:nickel>, <exnihilocreatio:item_ore_nickel:2>);
Blacklist.addRecipe(<liquid:nickel>, <thermalfoundation:material:69>);
Blacklist.addRecipe(<liquid:nickel>, <thermalfoundation:material:133>);
Blacklist.addRecipe(<liquid:nickel>, <thermalfoundation:material:197>);
Blacklist.addRecipe(<liquid:nickel>, <thermalfoundation:material:261>);
Blacklist.addRecipe(<liquid:nickel>, <thermalfoundation:material:325>);
Blacklist.addRecipe(<liquid:nickel>, <thermalfoundation:storage:5>);
Blacklist.addRecipe(<liquid:nickel>, <thermalfoundation:armor.helmet_nickel>);
Blacklist.addRecipe(<liquid:nickel>, <thermalfoundation:armor.plate_nickel>);
Blacklist.addRecipe(<liquid:nickel>, <thermalfoundation:armor.legs_nickel>);
Blacklist.addRecipe(<liquid:nickel>, <thermalfoundation:armor.boots_nickel>);
Blacklist.addRecipe(<liquid:nickel>, <thermalfoundation:tool.bow_nickel>);
Blacklist.addRecipe(<liquid:invar>, <thermalfoundation:tool.sickle_invar>);
Blacklist.addRecipe(<liquid:invar>, <thermalfoundation:material:162>);
Blacklist.addRecipe(<liquid:invar>, <thermalfoundation:material:226>);
Blacklist.addRecipe(<liquid:invar>, <thermalfoundation:material:98>);
Blacklist.addRecipe(<liquid:invar>, <thermalfoundation:storage_alloy:2>);
Blacklist.addRecipe(<liquid:invar>, <thermalfoundation:material:354>);
Blacklist.addRecipe(<liquid:invar>, <thermalfoundation:material:290>);
Blacklist.addRecipe(<liquid:invar>, <thermalfoundation:armor.helmet_invar>);
Blacklist.addRecipe(<liquid:invar>, <thermalfoundation:armor.plate_invar>);
Blacklist.addRecipe(<liquid:invar>, <thermalfoundation:armor.legs_invar>);
Blacklist.addRecipe(<liquid:invar>, <thermalfoundation:armor.boots_invar>);
Blacklist.addRecipe(<liquid:invar>, <thermalfoundation:tool.bow_invar>);
Blacklist.addRecipe(<liquid:invar>, <thermalfoundation:tool.sickle_invar>);
Blacklist.addRecipe(<liquid:constantan>, <thermalfoundation:tool.sickle_constantan>);
Blacklist.addRecipe(<liquid:constantan>, <thermalfoundation:tool.sword_constantan>);
Blacklist.addRecipe(<liquid:constantan>, <thermalfoundation:tool.hoe_constantan>);
Blacklist.addRecipe(<liquid:constantan>, <thermalfoundation:material:100>);
Blacklist.addRecipe(<liquid:constantan>, <thermalfoundation:storage_alloy:4>);
Blacklist.addRecipe(<liquid:constantan>, <thermalfoundation:material:164>);
Blacklist.addRecipe(<liquid:constantan>, <thermalfoundation:material:228>);
Blacklist.addRecipe(<liquid:constantan>, <thermalfoundation:material:292>);
Blacklist.addRecipe(<liquid:constantan>, <thermalfoundation:material:356>);
Blacklist.addRecipe(<liquid:constantan>, <thermalfoundation:armor.helmet_constantan>);
Blacklist.addRecipe(<liquid:constantan>, <thermalfoundation:armor.plate_constantan>);
Blacklist.addRecipe(<liquid:constantan>, <thermalfoundation:armor.legs_constantan>);
Blacklist.addRecipe(<liquid:constantan>, <thermalfoundation:armor.boots_constantan>);
Blacklist.addRecipe(<liquid:constantan>, <thermalfoundation:tool.bow_constantan>);
Blacklist.addRecipe(<liquid:dragonsteel_fire>, <iceandfire:dragonsteel_fire_block>);
Blacklist.addRecipe(<liquid:dragonsteel_fire>, <iceandfire:dragonsteel_fire_ingot>);
Blacklist.addRecipe(<liquid:dragonsteel_fire>, <iceandfire:dragonarmor_dragonsteel_fire>);
Blacklist.addRecipe(<liquid:dragonsteel_fire>, <iceandfire:dragonarmor_dragonsteel_fire:1>);
Blacklist.addRecipe(<liquid:dragonsteel_fire>, <iceandfire:dragonarmor_dragonsteel_fire:2>);
Blacklist.addRecipe(<liquid:dragonsteel_fire>, <iceandfire:dragonarmor_dragonsteel_fire:3>);
Blacklist.addRecipe(<liquid:dragonsteel_fire>, <iceandfire:dragonsteel_fire_helmet>);
Blacklist.addRecipe(<liquid:dragonsteel_fire>, <iceandfire:dragonsteel_fire_chestplate>);
Blacklist.addRecipe(<liquid:dragonsteel_fire>, <iceandfire:dragonsteel_fire_leggings>);
Blacklist.addRecipe(<liquid:dragonsteel_fire>, <iceandfire:dragonsteel_fire_boots>);
Blacklist.addRecipe(<liquid:dragonsteel_ice>, <iceandfire:dragonarmor_dragonsteel_ice>);
Blacklist.addRecipe(<liquid:dragonsteel_ice>, <iceandfire:dragonarmor_dragonsteel_ice:1>);
Blacklist.addRecipe(<liquid:dragonsteel_ice>, <iceandfire:dragonarmor_dragonsteel_ice:2>);
Blacklist.addRecipe(<liquid:dragonsteel_ice>, <iceandfire:dragonarmor_dragonsteel_ice:3>);
Blacklist.addRecipe(<liquid:dragonsteel_ice>, <iceandfire:dragonsteel_ice_helmet>);
Blacklist.addRecipe(<liquid:dragonsteel_ice>, <iceandfire:dragonsteel_ice_chestplate>);
Blacklist.addRecipe(<liquid:dragonsteel_ice>, <iceandfire:dragonsteel_ice_leggings>);
Blacklist.addRecipe(<liquid:dragonsteel_ice>, <iceandfire:dragonsteel_ice_boots>);
Blacklist.addRecipe(<liquid:dragonsteel_ice>, <iceandfire:dragonsteel_ice_block>);
Blacklist.addRecipe(<liquid:dragonsteel_ice>, <iceandfire:dragonsteel_ice_ingot>);
Blacklist.addRecipe(<liquid:uranium>, <geolosys:cluster:9>);
Blacklist.addRecipe(<liquid:osmium>, <geolosys:cluster:12>);