import mods.recipestages.Recipes;
import mods.ItemStages;
import crafttweaker.item.IItemStack;

val itemsIndustrialAge = [
    <forestry:refractory>,
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "water", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "lava", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "iron", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "pigiron", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "cobalt", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "ardite", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "manyullyn", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "knightslime", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "alubrass", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "brass", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "liquiddeuterium", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "brine", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "liquidsodium", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "liquidethene", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "liquidhydrogenchloride", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "sulfuricacid", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "liquidsulfurtrioxide", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "liquidsulfurdioxide", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "liquidchlorine", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "liquidoxygen", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "liquidhydrogen", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "aluminum", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "steel", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "electrum", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "silver", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "nickel", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "lead", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "zinc", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "bronze", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "tin", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "copper", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "liquidtritium", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "liquidfusionfuel", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "heavywater", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "steam", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "plantoil", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "ethanol", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "biodiesel", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "concrete", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "potion", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "ink", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "ink_cyan", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "ink_magenta", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "ink_yellow", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "sulfuric_acid", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "hydrofluoric_acid", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "nitric_acid", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "hydrogen", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "milk_goat", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "milk_friesian", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "milk_holstein", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "slop", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "fiery_essence", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "knightmetal", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "fierymetal", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "hot_spring_water", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "poison", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "blood", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "honey", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "polluted_water", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "crystaloil", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "refinedcanolaoil", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "canolaoil", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "methanol", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "chlorine", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "animania_honey", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "coal", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "refined_oil", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "refined_fuel", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "syrup", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "resin", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "tree_oil", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "seed_oil", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "biocrude", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "refined_biofuel", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "experience", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "potion_lingering", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "redstone", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "glowstone", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "ender", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "pyrotheum", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "soularium", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "pulsating_iron", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "conductive_iron", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "redstone_alloy", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "vibrant_alloy", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "energetic_alloy", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "electrical_steel", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "enderium", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "lumium", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "signalum", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "constantan", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "invar", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "iridium", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "platinum", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "mana", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "petrotheum", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "aerotheum", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "cryotheum", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "construction_alloy", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "fluidcalcium", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "fluidcalciumcarbonate", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "fluiddeuterium", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "fluidglyceryl", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "fluidhelium", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "fluidheliumplasma", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "fluidlithium", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "fluidmercury", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "fluidnitrocoalfuel", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "fluidnitrofuel", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "fluidnitrogendioxide", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "fluidcarbonfiber", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "fluidsilicon", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "ice", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "for.honey", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "biomass", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "bio.ethanol", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "fluidbiofuel", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "fluidelectrolyzedwater", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "fluidcompressedair", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "fluidoil", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "fluidnitrodiesel", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "fluiddiesel", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "fluidsodiumsulfide", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "fluidnitrocarbon", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "fluidwolframium", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "fluidsodiumpersulfate", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "fluidsodium", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "juice", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "milk", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "seed.oil", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "uranium", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "fuel", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "menrilresin", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "liquidchorus", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "witchwater", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "fossil_tar", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "methane", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "atmosphericgases", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "liquidmethane", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "liquidnitrogen", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "nitrogen", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "carbondioxide", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "argon", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "liquidargon", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "helium", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "boron11", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "boron10", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "boron", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "deuterium", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "distwater", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "napalm", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "gasoline", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "dragonsteel_ice", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "syngas", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "protein", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "mutagen", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "heliumhydrogen", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "ethane", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "helium3", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "liquidethanemethane", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "lithium6", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "hard_carbon", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "tough", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "condensate_water", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "beryllium", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "manganese_dioxide", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "sulfur", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "liquidhelium", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "liquid_nitrogen", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "neutron", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "radaway", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "radaway_slow", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "fluorine", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "carbon_dioxide", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "carbon_monoxide", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "ethene", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "milk_chocolate", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "dark_chocolate", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "unsweetened_chocolate", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "chocolate_liquor", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "borax_solution", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "potassium_hydroxide_solution", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "sodium_hydroxide_solution", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "sodium_fluoride_solution", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "fluorite_water", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "boric_acid", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "sulfur_trioxide", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "sulfur_dioxide", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "oxygen_difluoride", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "fluoromethane", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "hydrated_gelatin", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "lif", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "flibe", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "high_pressure_steam", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "exhaust_steam", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "low_pressure_steam", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "sodium", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "potassium", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "nak_hot", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "sic_vapor", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "uranium_238_fluoride_flibe", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "uranium_238_fluoride", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "uranium_238", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "uranium_235_fluoride", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "uranium_233_fluoride_flibe", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "uranium_233_fluoride", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "uranium_233", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "thorium_230_fluoride", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "thorium_230", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "plutonium_fluoride", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "plutonium", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "uranium_fluoride", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "thorium_fluoride_flibe", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "thorium", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "alumina", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "neptunium_236", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "neptunium_236_fluoride", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "neptunium_236_fluoride_flibe", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "neptunium_237_fluoride", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "neptunium_237_fluoride_flibe", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "plutonium_238", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "plutonium_238_fluoride_flibe", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "plutonium_239_fluoride", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "plutonium_239_fluoride_flibe", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "plutonium_241_fluoride", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "plutonium_242", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "plutonium_242_fluoride", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "plutonium_242_fluoride_flibe", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "americium_241_fluoride", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "americium_241_fluoride_flibe", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "americium_242", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "americium_242_fluoride_flibe", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "americium_243", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "americium_243_fluoride_flibe", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "curium_243_fluoride", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "curium_243_fluoride_flibe", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "curium_245", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "curium_245_fluoride", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "curium_246", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "curium_246_fluoride", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "curium_246_fluoride_flibe", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "curium_247_fluoride", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "curium_247_fluoride_flibe", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "berkelium_247_fluoride", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "berkelium_247_fluoride_flibe", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "fuel_leu_233_fluoride_flibe", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "fuel_leu_233_fluoride", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "fuel_leu_233", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "fuel_tbu_fluoride_flibe", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "fuel_tbu", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "californium_252_fluoride_flibe", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "californium_252", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "californium_251_fluoride_flibe", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "californium_251", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "californium_250_fluoride_flibe", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "californium_250_fluoride", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "californium_250", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "californium_249_fluoride_flibe", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "californium_249_fluoride", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "californium_249", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "berkelium_248_fluoride", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "fuel_heu_233", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "fuel_heu_233_fluoride_flibe", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "fuel_leu_235", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "fuel_leu_235_fluoride_flibe", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "fuel_heu_235", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "fuel_heu_235_fluoride_flibe", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "fuel_len_236", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "fuel_len_236_fluoride_flibe", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "fuel_hen_236", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "fuel_hen_236_fluoride_flibe", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "fuel_lep_239", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "fuel_lep_239_fluoride_flibe", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "fuel_hep_239", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "fuel_hep_239_fluoride", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "fuel_hep_239_fluoride_flibe", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "fuel_lecm_245_fluoride_flibe", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "fuel_lecm_245_fluoride", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "fuel_lecm_245", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "fuel_hecm_243_fluoride_flibe", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "fuel_hecm_243_fluoride", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "fuel_hecm_243", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "fuel_lecm_243_fluoride", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "fuel_lecm_243", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "fuel_hea_242_fluoride", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "fuel_lea_242_fluoride_flibe", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "fuel_lea_242_fluoride", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "fuel_lea_242", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "fuel_hep_241_fluoride_flibe", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "fuel_hep_241_fluoride", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "fuel_lep_241_fluoride_flibe", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "fuel_lep_241_fluoride", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "fuel_lep_241", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "fuel_hecm_245", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "fuel_hecm_245_fluoride", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "fuel_hecm_245_fluoride_flibe", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "fuel_lecm_247_fluoride", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "fuel_lecm_247_fluoride_flibe", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "fuel_hecm_247", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "fuel_leb_248", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "fuel_leb_248_fluoride", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "fuel_heb_248", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "fuel_heb_248_fluoride", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "fuel_heb_248_fluoride_flibe", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "fuel_lecf_249_fluoride", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "fuel_lecf_249_fluoride_flibe", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "fuel_hecf_249", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "fuel_hecf_249_fluoride", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "fuel_hecf_249_fluoride_flibe", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "depleted_fuel_heu_235_fluoride_flibe", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "depleted_fuel_heu_235_fluoride", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "depleted_fuel_heu_235", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "depleted_fuel_leu_235_fluoride", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "depleted_fuel_heu_233_fluoride_flibe", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "depleted_fuel_heu_233_fluoride", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "depleted_fuel_leu_233_fluoride_flibe", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "depleted_fuel_leu_233", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "depleted_fuel_tbu_fluoride_flibe", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "depleted_fuel_tbu_fluoride", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "depleted_fuel_tbu", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "fuel_hecf_251_fluoride_flibe", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "fuel_hecf_251_fluoride", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "fuel_hecf_251", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "fuel_lecf_251_fluoride_flibe", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "fuel_lecf_251", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "depleted_fuel_len_236", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "depleted_fuel_len_236_fluoride", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "depleted_fuel_len_236_fluoride_flibe", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "depleted_fuel_hen_236_fluoride", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "depleted_fuel_lep_239", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "depleted_fuel_lep_239_fluoride", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "depleted_fuel_hep_239", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "depleted_fuel_hep_239_fluoride", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "depleted_fuel_lep_241", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "depleted_fuel_lep_241_fluoride", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "depleted_fuel_lep_241_fluoride_flibe", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "depleted_fuel_hep_241_fluoride", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "depleted_fuel_lea_242", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "depleted_fuel_lea_242_fluoride", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "depleted_fuel_hecm_247_fluoride_flibe", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "depleted_fuel_hecm_247", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "depleted_fuel_lecm_247_fluoride", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "depleted_fuel_lecm_247", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "depleted_fuel_hecm_245_fluoride_flibe", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "depleted_fuel_hecm_245", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "depleted_fuel_lecm_245_fluoride_flibe", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "depleted_fuel_lecm_245_fluoride", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "depleted_fuel_hecm_243_fluoride_flibe", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "depleted_fuel_hecm_243_fluoride", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "depleted_fuel_lecm_243_fluoride", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "depleted_fuel_lecm_243", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "depleted_fuel_hea_242_fluoride_flibe", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "depleted_fuel_hea_242_fluoride", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "depleted_fuel_leb_248", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "depleted_fuel_leb_248_fluoride", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "depleted_fuel_leb_248_fluoride_flibe", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "depleted_fuel_heb_248_fluoride", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "depleted_fuel_heb_248_fluoride_flibe", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "depleted_fuel_lecf_249", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "depleted_fuel_lecf_249_fluoride", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "depleted_fuel_lecf_249_fluoride_flibe", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "depleted_fuel_hecf_249_fluoride", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "depleted_fuel_hecf_249_fluoride_flibe", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "depleted_fuel_lecf_251", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "depleted_fuel_lecf_251_fluoride_flibe", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "depleted_fuel_hecf_251", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "depleted_fuel_hecf_251_fluoride", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "redstone_nak", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "redstone_nak_hot", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "quartz", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "emerald", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "iron_nak_hot", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "cryotheum_nak_hot", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "cryotheum_nak", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "ender_nak_hot", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "ender_nak", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "liquidhelium_nak_hot", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "diamond_nak_hot", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "diamond_nak", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "lapis_nak_hot", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "lapis_nak", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "lapis", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "glowstone_nak", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "gold_nak_hot", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "gold_nak", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "quartz_nak_hot", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "quartz_nak", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "emerald_nak", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "emerald_nak_hot", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "copper_nak_hot", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "tin_nak", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "tin_nak_hot", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "magnesium_nak", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "crystallize_water_fluid", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "crystallize_lava_fluid", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "cheese_of_milk_gas", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "infected_water_fluid", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "helium_gas", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "purify_water_fluid", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "stagnant_water", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "tar", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "rubber", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "rocket_fuel", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "vapor_of_levity", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "nutrient_distillation", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "vampirismblood", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "pewterfluid", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "octine", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "voidmetal", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "terrasteel", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "elementium", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "soulforgedsteel", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "hellfire", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "starmetal", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "fog", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "fire_water", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "xpjuice", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "liquid_sunshine", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "flux_goo", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "liquid_death", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "purifying_fluid", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "obsidian", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "clay", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "blueslime", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "purpleslime", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "tannin", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "brine_netjry", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "waste", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "bitumen", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "bitumen_boiling", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "paraffin", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "fuelgc", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "oilgc", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "astralsorcery.liquidstarlight", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "smoke", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "ovis_atre_milk", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "magma_basaltic", Amount: 1000}}),
    <forestry:refractory:1>.withTag({"SmithsCore-CapData": {}, Fluid: {FluidName: "fluidpotassium", Amount: 1000}}),
    <forestry:engine_peat>,
    <forestry:engine_biogas>,
    <forestry:engine_clockwork>,
    <forestry:ffarm>.withTag({FarmBlock: 0, "SmithsCore-CapData": {}}),
    <forestry:ffarm>.withTag({FarmBlock: 1, "SmithsCore-CapData": {}}),
    <forestry:ffarm>.withTag({FarmBlock: 2, "SmithsCore-CapData": {}}),
    <forestry:ffarm>.withTag({FarmBlock: 3, "SmithsCore-CapData": {}}),
    <forestry:ffarm>.withTag({FarmBlock: 4, "SmithsCore-CapData": {}}),
    <forestry:ffarm>.withTag({FarmBlock: 5, "SmithsCore-CapData": {}}),
    <forestry:ffarm>.withTag({FarmBlock: 6, "SmithsCore-CapData": {}}),
    <forestry:ffarm>.withTag({FarmBlock: 7, "SmithsCore-CapData": {}}),
    <forestry:ffarm>.withTag({FarmBlock: 8, "SmithsCore-CapData": {}}),
    <forestry:ffarm>.withTag({FarmBlock: 9, "SmithsCore-CapData": {}}),
    <forestry:ffarm>.withTag({FarmBlock: 10, "SmithsCore-CapData": {}}),
    <forestry:ffarm:2>.withTag({FarmBlock: 0, "SmithsCore-CapData": {}}),
    <forestry:ffarm:2>.withTag({FarmBlock: 1, "SmithsCore-CapData": {}}),
    <forestry:ffarm:2>.withTag({FarmBlock: 2, "SmithsCore-CapData": {}}),
    <forestry:ffarm:2>.withTag({FarmBlock: 3, "SmithsCore-CapData": {}}),
    <forestry:ffarm:2>.withTag({FarmBlock: 4, "SmithsCore-CapData": {}}),
    <forestry:ffarm:2>.withTag({FarmBlock: 5, "SmithsCore-CapData": {}}),
    <forestry:ffarm:2>.withTag({FarmBlock: 6, "SmithsCore-CapData": {}}),
    <forestry:ffarm:2>.withTag({FarmBlock: 7, "SmithsCore-CapData": {}}),
    <forestry:ffarm:2>.withTag({FarmBlock: 8, "SmithsCore-CapData": {}}),
    <forestry:ffarm:2>.withTag({FarmBlock: 9, "SmithsCore-CapData": {}}),
    <forestry:ffarm:2>.withTag({FarmBlock: 10, "SmithsCore-CapData": {}}),
    <forestry:ffarm:3>.withTag({FarmBlock: 0, "SmithsCore-CapData": {}}),
    <forestry:ffarm:3>.withTag({FarmBlock: 1, "SmithsCore-CapData": {}}),
    <forestry:ffarm:3>.withTag({FarmBlock: 2, "SmithsCore-CapData": {}}),
    <forestry:ffarm:3>.withTag({FarmBlock: 3, "SmithsCore-CapData": {}}),
    <forestry:ffarm:3>.withTag({FarmBlock: 4, "SmithsCore-CapData": {}}),
    <forestry:ffarm:3>.withTag({FarmBlock: 5, "SmithsCore-CapData": {}}),
    <forestry:ffarm:3>.withTag({FarmBlock: 6, "SmithsCore-CapData": {}}),
    <forestry:ffarm:3>.withTag({FarmBlock: 7, "SmithsCore-CapData": {}}),
    <forestry:ffarm:3>.withTag({FarmBlock: 8, "SmithsCore-CapData": {}}),
    <forestry:ffarm:3>.withTag({FarmBlock: 9, "SmithsCore-CapData": {}}),
    <forestry:ffarm:3>.withTag({FarmBlock: 10, "SmithsCore-CapData": {}}),
    <forestry:ffarm:4>.withTag({FarmBlock: 0, "SmithsCore-CapData": {}}),
    <forestry:ffarm:4>.withTag({FarmBlock: 1, "SmithsCore-CapData": {}}),
    <forestry:ffarm:4>.withTag({FarmBlock: 2, "SmithsCore-CapData": {}}),
    <forestry:ffarm:4>.withTag({FarmBlock: 3, "SmithsCore-CapData": {}}),
    <forestry:ffarm:4>.withTag({FarmBlock: 4, "SmithsCore-CapData": {}}),
    <forestry:ffarm:4>.withTag({FarmBlock: 5, "SmithsCore-CapData": {}}),
    <forestry:ffarm:4>.withTag({FarmBlock: 6, "SmithsCore-CapData": {}}),
    <forestry:ffarm:4>.withTag({FarmBlock: 7, "SmithsCore-CapData": {}}),
    <forestry:ffarm:4>.withTag({FarmBlock: 8, "SmithsCore-CapData": {}}),
    <forestry:ffarm:4>.withTag({FarmBlock: 9, "SmithsCore-CapData": {}}),
    <forestry:ffarm:4>.withTag({FarmBlock: 10, "SmithsCore-CapData": {}}),
    <forestry:ffarm:5>.withTag({FarmBlock: 0, "SmithsCore-CapData": {}}),
    <forestry:ffarm:5>.withTag({FarmBlock: 1, "SmithsCore-CapData": {}}),
    <forestry:ffarm:5>.withTag({FarmBlock: 2, "SmithsCore-CapData": {}}),
    <forestry:ffarm:5>.withTag({FarmBlock: 3, "SmithsCore-CapData": {}}),
    <forestry:ffarm:5>.withTag({FarmBlock: 4, "SmithsCore-CapData": {}}),
    <forestry:ffarm:5>.withTag({FarmBlock: 5, "SmithsCore-CapData": {}}),
    <forestry:ffarm:5>.withTag({FarmBlock: 6, "SmithsCore-CapData": {}}),
    <forestry:ffarm:5>.withTag({FarmBlock: 7, "SmithsCore-CapData": {}}),
    <forestry:ffarm:5>.withTag({FarmBlock: 8, "SmithsCore-CapData": {}}),
    <forestry:ffarm:5>.withTag({FarmBlock: 10, "SmithsCore-CapData": {}}),
    <forestry:ffarm:5>.withTag({FarmBlock: 9, "SmithsCore-CapData": {}}),
    <forestry:crate>,
    <forestry:genetic_filter>,
    <forestry:bottler>,
    <forestry:carpenter>,
    <forestry:centrifuge>,
    <forestry:fermenter>,
    <forestry:moistener>,
    <forestry:squeezer>,
    <forestry:still>,
    <forestry:rainmaker>,
    <forestry:fabricator>,
    <forestry:raintank>,
    <forestry:miner_bag_t2>,
    <forestry:digger_bag_t2>,
    <forestry:forester_bag_t2>,
    <forestry:hunter_bag_t2>,
    <forestry:adventurer_bag_t2>,
    <forestry:builder_bag_t2>
] as IItemStack[];

for item in itemsIndustrialAge{
    ItemStages.addItemStage("IndustrialAge", item);
}